name: CD

on:
  release:
    types: [published]

jobs:
  deploy-docker-image:
    name: Deploy image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
      - name: Push the latest Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }} --all-tags
